#
# mq service
#
apiVersion: v1
kind: Service
metadata:
  name: mq

spec:
  type: NodePort
  selector:
    io.kompose.service: mq

  ports:
    - name: mq
      protocol: TCP
      port: 5672
      targetPort: 5672

---
#
# mq deployment + volume claim
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mq
  name: mq

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mq

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        io.kompose.service: mq

    spec:
      containers:
        - image: rabbitmq:3.8.19
          name: mq
          resources: {}
          #resources:
          #  limits:
          #    cpu: 150m
          #    memory: 128Mi
          #  requests:
          #    cpu: 25m
          #    memory: 64Mi

          ports:
            - containerPort: 5672
              protocol: TCP

          volumeMounts:
            - mountPath: /var/log/rabbitmq/mnesia
              name: mq-logs

            - mountPath: /var/lib/rabbitmq/mnesia
              name: mq-data

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: config
                  key: PRIMO_MQ_USERNAME

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: config
                  key: PRIMO_MQ_PASSWORD

      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mq-logs
          persistentVolumeClaim:
            claimName: mq-logs

        - name: mq-data
          persistentVolumeClaim:
            claimName: mq-data

status: {}

---
#
# mq volume claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-data
  labels:
    io.kompose.service: mq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
#
# mq volume claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-logs
  labels:
    io.kompose.service: mq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
