#
# API service
#
apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  ports:
    # Add a port for the debugger to connect
    - name: debug
      protocol: TCP
      port: 9232
      targetPort: 9232

---
#
# API deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    io.kompose.service: api

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api

  template:
    metadata:
      labels:
        io.kompose.service: api

    spec:
      containers:
        - image: primordialimages.azurecr.io/primo-api:latest
          name: api
          imagePullPolicy: Never
          resources: {}
          command:
            - yarn
            - start:worker:legacy

          volumeMounts:
            - name: dist
              mountPath: "/app/roles"
              readOnly: true
              mountPropagation: HostToContainer

          ports:
            - containerPort: 9232
              protocol: TCP

      volumes:
        - name: dist

          hostPath:
            path: /app/dist
