#
# pgadmin deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    io.kompose.service: pgadmin

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin

  template:
    metadata:
      labels:
        io.kompose.service: pgadmin

    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmin
        resources: {}
        env: 
          - name: PGADMIN_DEFAULT_EMAIL
            value: "user@domain.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "dev"

        ports:
          - containerPort: 80
            protocol: TCP


---

#
# pgadmin service
#
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels: 
    group: db

spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 8777
      targetPort: 5432
