#
# Secret declarations for staging and production environments.
# These secrets map to values in an Azure Key Vault.
#
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-key-vault

# Blank out the KV references defined in the base.
# Development configuration comes from your local "config.local.yml" so please add them there.
spec:
  provider: ""
  parameters:
    keyvaultName: ""
    tenantId: ""

    objects: |
      array:
        |
