#
# Spooler service
#
apiVersion: v1
kind: Service
metadata:
  name: spooler

spec:
  ports:
    # Add a port for the debugger to connect
    - name: debug
      protocol: TCP
      port: 9233
      targetPort: 9233

---
#
# Spooler deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spooler
  labels:
    io.kompose.service: spooler

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spooler

  template:
    metadata:
      labels:
        io.kompose.service: spooler

    spec:
      containers:
        - image: primordialimages.azurecr.io/primo-spooler:latest
          name: spooler
          imagePullPolicy: Never
          resources: {}
          command:
            - yarn
            - start:spooler:legacy

          volumeMounts:
            - name: dist
              mountPath: "/app/roles"
              readOnly: true
              mountPropagation: HostToContainer

          ports:
            - containerPort: 9233
              protocol: TCP

      volumes:
        - name: dist

          hostPath:
            path: /app/dist
