#
# Web deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    io.kompose.service: web

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web

  template:
    metadata:
      labels:
        io.kompose.service: web

    spec:
      containers:
        - image: primordialimages.azurecr.io/primordial-web:latest
          name: web
          imagePullPolicy: Never
          resources: {}

          # Mount the source code inside using delegated mount to improve
          # performance on non-linux OS's
          volumeMounts:
            - name: roles
              mountPath: "/app/roles"

      volumes:
        - name: roles
          hostPath:
            path: /app/roles
