apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret

spec:
  secretName: tls-secret
  dnsNames:

    # "Production" is really just staging at this point
    - "primo.mothership.io"

    - "staging.primo.mothership.io"
    - "staging.primordial.mothership.io"

  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
