bases:
  - ../../base
  - ../shared

resources:
  - namespace.yml
  - certificate.yml
  - cluster-issuer.yml
  - roles.yml

  # Resource quota not being used.
  #- resource-quota.yml

patchesStrategicMerge:
  - api.yml
  - ingress.yml
  - spooler.yml
  - worker.yml
  - secrets.yml