apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-key-vault
  namespace: staging
spec:
  provider: azure
  parameters:
    keyvaultName: "primo-vault-production"
    tenantId: "2259941a-29d5-41c6-b336-994324af3677"

    # This is a handle to the cluster's identity in Active Directory.
    userAssignedIdentityID: "e9f9f290-5171-4f09-8878-34935f802942"

    # This is the "user managed" identity flavour.
    # The cluster's identity flows through cluster -> node -> pod thanks to this setup.
    useVMManagedIdentity: "true"
