apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-key-vault
  namespace: staging
spec:
  provider: azure
  parameters:
    keyvaultName: "primo-vault-development"
    tenantId: "2259941a-29d5-41c6-b336-994324af3677"

    # This is a handle to the cluster's identity in Active Directory.
    #userAssignedIdentityID: "0da52771-b082-4629-b74e-dad34e72c96e"
    userAssignedIdentityID: "2b2c4bcc-c1b7-45bf-b29f-4785112dd37c"

    # This is the "user managed" identity flavour.
    # The cluster's identity flows through cluster -> node -> pod thanks to this setup.
    useVMManagedIdentity: "true"
